export const searchCategoryLink = [
  {
    id: 1,
    name: "All",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 2,
    name: "Arts & Crafts",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 3,
    name: "AutoMotive",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 4,
    name: "Baby",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 5,
    name: "Computers",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 6,
    name: "Music",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 7,
    name: "Electronics",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 8,
    name: "Kindle Store",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
      ,
    ],
  },
  {
    id: 9,
    name: "Prime Video",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 10,
    name: "Women's Fashions",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 11,
    name: "Men's Fashions",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 12,
    name: "Girls' Fashions",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 13,
    name: "Boys' Fashions",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 14,
    name: "Health & Household",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 15,
    name: "Home & Kitchen",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 16,
    name: "Video Games",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 17,
    name: "Software",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
  {
    id: 18,
    name: "Toy Games",
    link: "/",
    allCategories: [
      { id: 1, productName: "Gift Cards" },
      { id: 2, productName: "Nail palish" },
      { id: 3, productName: "Gift Card Happy birthday" },
      { id: 4, productName: "Book" },
      { id: 5, productName: "Mobile Phone" },
      { id: 6, productName: "Mobile" },
      { id: 7, productName: "Mobile desk" },
      { id: 8, productName: "Mobile hotspot" },
      { id: 9, productName: "laptop stand" },
      { id: 10, productName: "laptop desk" },
      { id: 11, productName: "camera" },
      { id: 12, productName: "camera for computer" },
      { id: 13, productName: "camera for kids" },
      { id: 14, productName: "game" },
      { id: 15, productName: "game chair" },
      { id: 16, productName: "game boy" },
      { id: 17, productName: "shirts" },
      { id: 18, productName: "shirts for man" },
      { id: 19, productName: "shirts for women" },
      { id: 20, productName: "shirts press" },
      { id: 21, productName: "car" },
      { id: 22, productName: "car for children" },
      { id: 23, productName: "cars" },
    ],
  },
];
